# Generated by Django 5.2.6 on 2025-09-16 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_usuario_alter_perfilusuario_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Progreso',
        ),
    ]
