# Generated by Django 5.2.6 on 2025-09-12 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgresoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.CharField(max_length=100, verbose_name='Actividad')),
                ('progreso', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Progreso (%)')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Inicio')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('completado', models.BooleanField(default=False, verbose_name='Completado')),
                ('resultado', models.TextField(blank=True, null=True, verbose_name='Resultado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Progreso de Usuario',
                'verbose_name_plural': 'Progresos de Usuarios',
                'ordering': ['-fecha_actualizacion'],
                'unique_together': {('usuario', 'actividad')},
            },
        ),
        migrations.CreateModel(
            name='LogProgreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progreso_anterior', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Progreso Anterior')),
                ('progreso_nuevo', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Progreso Nuevo')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Cambio')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción del Cambio')),
                ('progreso_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='progreso_usuario.progresousuario')),
            ],
            options={
                'verbose_name': 'Log de Progreso',
                'verbose_name_plural': 'Logs de Progreso',
                'ordering': ['-fecha_cambio'],
            },
        ),
    ]
